/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bill;
import java.sql.*;
import billing.DbCon;
import billing.Demo;

import java.util.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import com.itextpdf.kernel.pdf.PdfWriter; 
import com.itextpdf.text.Paragraph;
import com.itextpdf.text;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.event.KeyEvent;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;



import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Bill extends javax.swing.JFrame {
    public int finalTotal=0;
    

    /**
     * Creates new form Bill
     */
    public Bill() {
        initComponents();
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        jLabel21.setText(dFormat.format(date));
        
        DateTimeFormatter dft = DateTimeFormatter.ofPattern("HH:mm:SS");
        LocalDateTime now = LocalDateTime.now();
        jLabel22.setText(dft.format(now));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void autoBillno(){
        
    try{
    DbCon con = new DbCon();
    
    }catch(Exception e){}
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        contactnumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cadders = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cemail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pmodelno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pcname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        prate = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        pdesc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        pqty = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tamt = new javax.swing.JTextField();
        pamt = new javax.swing.JTextField();
        prmt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Candara", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Electronic Device Billing System");
        jLabel1.setAlignmentX(100.0F);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 6, 691, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer Details");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 277, 110, 45));

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contact Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 277, 100, 45));

        contactnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactnumberActionPerformed(evt);
            }
        });
        contactnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contactnumberKeyPressed(evt);
            }
        });
        getContentPane().add(contactnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 277, 103, 45));

        jLabel4.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 277, -1, 45));

        cname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnameActionPerformed(evt);
            }
        });
        cname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cnameKeyPressed(evt);
            }
        });
        getContentPane().add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 277, 132, 45));

        jLabel5.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 277, 54, 45));

        cadders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caddersActionPerformed(evt);
            }
        });
        cadders.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                caddersKeyPressed(evt);
            }
        });
        getContentPane().add(cadders, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 277, 106, 45));

        jLabel6.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(817, 277, 67, 45));

        cemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cemailActionPerformed(evt);
            }
        });
        cemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cemailKeyPressed(evt);
            }
        });
        getContentPane().add(cemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 277, 145, 45));

        jLabel7.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Product Details");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 363, 98, 45));

        jLabel8.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Model Number");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 363, -1, 45));

        pmodelno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmodelnoActionPerformed(evt);
            }
        });
        pmodelno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pmodelnoKeyPressed(evt);
            }
        });
        getContentPane().add(pmodelno, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 360, 103, 50));

        jLabel9.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 360, 56, 50));

        pname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnameActionPerformed(evt);
            }
        });
        pname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pnameKeyPressed(evt);
            }
        });
        getContentPane().add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 360, 90, 50));

        jLabel10.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Comapny Name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 360, -1, 50));

        pcname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcnameActionPerformed(evt);
            }
        });
        pcname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pcnameKeyPressed(evt);
            }
        });
        getContentPane().add(pcname, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 360, 91, 50));

        jLabel11.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Rate");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(802, 366, 49, 39));

        prate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prateActionPerformed(evt);
            }
        });
        prate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                prateKeyPressed(evt);
            }
        });
        getContentPane().add(prate, new org.netbeans.lib.awtextra.AbsoluteConstraints(869, 362, 91, 47));

        jLabel13.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Description");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(978, 363, 78, 45));

        pdesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdescActionPerformed(evt);
            }
        });
        pdesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pdescKeyPressed(evt);
            }
        });
        getContentPane().add(pdesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1062, 362, 119, 46));

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 369, -1, 34));

        jLabel14.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Quantity");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1199, 360, 62, 50));

        pqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pqtyActionPerformed(evt);
            }
        });
        pqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pqtyKeyPressed(evt);
            }
        });
        getContentPane().add(pqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(1267, 361, 85, 49));

        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Model No", "Name", "Description", "Rate", "Quantity", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 687, 146));

        jLabel15.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Calculation details ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 446, 116, 33));

        jLabel16.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Total Amount");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 494, 84, -1));

        jLabel17.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Paid Amount");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 535, 84, -1));

        jLabel18.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Return Amout");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 575, 84, -1));

        tamt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tamtKeyPressed(evt);
            }
        });
        getContentPane().add(tamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(888, 491, 112, -1));

        pamt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pamtActionPerformed(evt);
            }
        });
        getContentPane().add(pamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(888, 532, 112, -1));

        prmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prmtActionPerformed(evt);
            }
        });
        getContentPane().add(prmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(888, 572, 112, -1));

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 450, -1, -1));

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1063, 553, -1, -1));

        jLabel12.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Date");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 101, 47));

        jLabel19.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Time");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 101, 47));

        jLabel20.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Billing Details");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 180, 45));

        jLabel21.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("jLabel21");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 110, 47));

        jLabel22.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("jLabel22");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 100, 40));

        jLabel24.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Bill Number");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 130, 101, 47));

        jLabel25.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 130, 110, 47));

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 500, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg-form.png"))); // NOI18N
        jLabel23.setText("jLabel23");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1850, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contactnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactnumberActionPerformed
        // TODO add your handling code here:
        String conatactno = contactnumber.getText();
         try{
               
              DbCon con = new DbCon();
              String q = "select * from `billingsys`.`customer` where CustNo like '"+conatactno+"'";
              ResultSet rs=con.st.executeQuery(q);
              if(rs.next())
              {
                  cname.setText(rs.getString(1));
                  cadders.setText(rs.getString(3));
                  cemail.setText(rs.getString(4));
              
              }
              else
              {
                cname.setText("");
                cadders.setText("");
                cemail.setText("");
              
              }
              
                
           }catch(SQLException e){
           JOptionPane.showMessageDialog(null, e);
           }
           
        if(conatactno.length()==10)
        {
            contactnumber.setEditable(true);
        
        }
        else
        {
             contactnumber.setEditable(false);
        }
    }//GEN-LAST:event_contactnumberActionPerformed

    private void cnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnameActionPerformed

    private void caddersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caddersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caddersActionPerformed

    private void cemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cemailActionPerformed

    private void pmodelnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmodelnoActionPerformed
        // TODO add your handling code here:
        String mno = pmodelno.getText();
         try{
               
              DbCon con = new DbCon();
              String q = "select * from `billingsys`.`product1` where ModelNO like '"+mno+"'";
              ResultSet rs=con.st.executeQuery(q);
              if(rs.next())
              {
                  pname.setText(rs.getString(3));
                  pcname.setText(rs.getString(4));
                  prate.setText(rs.getString(5));
                  pdesc.setText(rs.getString(6));
                  pqty.setText("0");
              }
              else
              {
                cname.setText("");
                cadders.setText("");
                cemail.setText("");
              
              }
              
                
           }catch(SQLException e){
           JOptionPane.showMessageDialog(null, e);
           }
        
    }//GEN-LAST:event_pmodelnoActionPerformed

    private void pnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnameActionPerformed

    private void pcnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pcnameActionPerformed

    private void prateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prateActionPerformed

    private void pdescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pdescActionPerformed

    private void pqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pqtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pqtyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int price = Integer.parseInt(prate.getText());
        int qty = Integer.parseInt(pqty.getText());
        int total = price*qty;
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[]{pmodelno.getText(),pname.getText(),pdesc.getText(),price,qty,total});
        finalTotal= finalTotal + total;
        String finalTotal1= String.valueOf(finalTotal);
        tamt.setText(finalTotal1);
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pamtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pamtActionPerformed
        // TODO add your handling code here:
        String paidAmt = pamt.getText();
        int paidAmt1= Integer.parseInt(paidAmt);
        finalTotal=paidAmt1-finalTotal;
        String finalTotal1 = String.valueOf(finalTotal);
        prmt.setText(finalTotal1);
        prmt.setEditable(false);
    }//GEN-LAST:event_pamtActionPerformed

    private void prmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prmtActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         new Demo().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String cname1 = cname.getText();
        String contactnumber1 = contactnumber.getText();
        String cadders1 = cadders.getText();
        String cemail1 = cemail.getText();


        String path = "D:\\TYBCA\\Project Sem 6\\Billing System\\BILL PDF";
   
        
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
       
        try
        {
            PdfWriter.getInstance(doc, new FileOutputStream(path=""+cname1+" "+jLabel21.getText()+".pdf"));
            doc.open();
            Paragraph paragraph1=new Paragraph("                                 Electronic Device Shop(Billing Management System)\n\n                                             Contact Number:9657236189 \n\n");
            doc.add(paragraph1);
            Paragraph paragraph2 = new Paragraph("Date & Time: " + jLabel21.getText() + " " + jLabel22.getText() + "\nBill ID: " + jLabel25.getText()
                    +"\nCustomer Details :\nName: " + cname1 + "\nContact No: " + contactnumber1+ "\nEmail: " + cemail1+ "\nAddress: " + cadders1+"\n\n");
            doc.add(paragraph2);
             PdfPTable tb1 = new PdfPTable(6);
             tb1.addCell("Model Number");
            tb1.addCell("Name");
            tb1.addCell("Description");
            tb1.addCell("Rate");
            tb1.addCell("Quantity");
            tb1.addCell("Sub Total");
            for(int i=0;i<jTable1.getRowCount();i++)
            {
                String m = jTable1.getValueAt(i,0).toString();
                String n= jTable1.getValueAt(i,1).toString();
                String d= jTable1.getValueAt(i,2).toString();
                String r= jTable1.getValueAt(i,3).toString();
                String q= jTable1.getValueAt(i,4).toString();
                String s= jTable1.getValueAt(i,5).toString();

               tb1.addCell(m);
               tb1.addCell(n);
               tb1.addCell(d);
               tb1.addCell(r);
               tb1.addCell(q);
               tb1.addCell(s);
              
            }
            doc.add(tb1);
               Paragraph paragraph3=new Paragraph("\nTotal:"+tamt.getText()+"\nPaid Amount:"+pamt.getText()+"\nReturn Amount:"+prmt.getText()+"\n\nThank you for Visiting ! Please come Again. \nElectronic Device Shop ");

             doc.add(paragraph3);
            JOptionPane.showMessageDialog(null, "Bill Generated");
            setVisible(true);
            //new Demo().setVisible(true);


        
        }
        catch(Exception e)
                {
                 JOptionPane.showMessageDialog(null,e); 
                }
         doc.close();
         
         
         String mno,name,desc,rate,qty,total;
         DefaultTableModel tblmodel  = (DefaultTableModel)jTable1.getModel();
         try{
         Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/billingsys", "root", "Password@123");
         String  Billid =jLabel25.getText();
         int bid = Integer.parseInt(Billid);
        
         
         
         for(int i =0;i<tblmodel.getRowCount();i++)
         {
             mno = tblmodel.getValueAt(i,0).toString();
             name = tblmodel.getValueAt(i,1).toString();
             desc = tblmodel.getValueAt(i,2).toString();
             rate = tblmodel.getValueAt(i,3).toString();
             qty = tblmodel.getValueAt(i,4).toString();
             total = tblmodel.getValueAt(i,5).toString();
             
             String query="Insert into `billingsys`.`bill` values(?,?,?,?,?,?,?)";
             PreparedStatement pst = con.prepareStatement(query);
             pst.setString(1,name);
             pst.setString(2, desc);
              pst.setString(3, rate);
               pst.setString(4, qty);
                pst.setString(5, total);
                pst.setInt(6, bid);
                pst.setString(7,mno);         
           
                
                pst.executeUpdate();
             
             
             
         }
         
         
         
         }catch(Exception e){}
         
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
              // TODO add your handling code here:
        try{
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/billingsys", "root", "Password@123");
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            String q ="Select max(BillID) from `billingsys`.`bill`";
            ResultSet rs = st.executeQuery(q);
            if(rs.first()){
                int id = rs.getInt(1);
                id = id+1;
                String str = String.valueOf(id);
                jLabel25.setText(str);
                
            }
            else{
                jLabel25.setText("1");
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void cnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnameKeyPressed
        // TODO add your handling code here:
        cname.setEditable(false);
    }//GEN-LAST:event_cnameKeyPressed

    private void caddersKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caddersKeyPressed
        // TODO add your handling code here:
        cadders.setEditable(false);
    }//GEN-LAST:event_caddersKeyPressed

    private void cemailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cemailKeyPressed
        // TODO add your handling code here:
        cemail.setEditable(false);
    }//GEN-LAST:event_cemailKeyPressed

    private void pmodelnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pmodelnoKeyPressed
        // TODO add your handling code here:
        pmodelno.setEditable(true);
    }//GEN-LAST:event_pmodelnoKeyPressed

    private void pnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnameKeyPressed
        // TODO add your handling code here:
        pname.setEditable(false);
    }//GEN-LAST:event_pnameKeyPressed

    private void pcnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pcnameKeyPressed
        // TODO add your handling code here:
        pcname.setEditable(false);
    }//GEN-LAST:event_pcnameKeyPressed

    private void prateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prateKeyPressed
        // TODO add your handling code here:
        prate.setEditable(false);
    }//GEN-LAST:event_prateKeyPressed

    private void pdescKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pdescKeyPressed
        // TODO add your handling code here:
        pdesc.setEditable(false);
    }//GEN-LAST:event_pdescKeyPressed

    private void tamtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tamtKeyPressed
        // TODO add your handling code here:
        tamt.setEditable(false);
    }//GEN-LAST:event_tamtKeyPressed

    private void pqtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pqtyKeyPressed
        // TODO add your handling code here:
        char c =evt.getKeyChar();
          if(Character.isDigit(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        {
            pqty.setEditable(true);
            String qty = pqty.getText();
            String m= pmodelno.getText();
            String date = jLabel21.getText();
            
            int qty1 = Integer.parseInt(qty);
            String tqty = null;
            try{
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/billingsys", "root", "Password@123");
             PreparedStatement pst = con.prepareStatement("SELECT * FROM `billingsys`.`product1` WHERE Modelno=?");
              pst.setString(1, m);
               ResultSet rs = pst.executeQuery();
             while(rs.next())
             {
                 tqty = rs.getString(7);
             }
                
            int tqty1 =Integer.parseInt(tqty);
            if(tqty1<qty1)
            {
               JOptionPane.showMessageDialog(null,"Out Of Stock");
            }
            else{
                tqty1 = tqty1-qty1;
                String tqty2 = String.valueOf(tqty1);
                DbCon con1 = new DbCon();
                 String query="UPDATE `billingsys`.`product1` SET `Time`='"+date+"',`pqty` = '"+tqty2+"' WHERE (`Modelno` = '"+m+"')";
              
                  int n=con1.st.executeUpdate(query);
                   if(n==1)
              {
                  JOptionPane.showMessageDialog(null, "Stock updated");
                  
              }
                
            }
            
             
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
           
        }
        else
        {
             pqty.setEditable(false);
        }
    }//GEN-LAST:event_pqtyKeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        cadders.setText("");
        cemail.setText("");
        cname.setText("");
        contactnumber.setText("");
        pamt.setText("");
        pcname.setText("");
        pdesc.setText("");
        pmodelno.setText("");
        pname.setText("");
        pqty.setText("");
        prate.setText("");
        prmt.setText("");
        tamt.setText("");
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"Model no","Name","Description","Rate","Quantity","Total"}));

        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void contactnumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactnumberKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isDigit(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        {
            contactnumber.setEditable(true);
        }
        else
        {
             contactnumber.setEditable(false);
        }
         String Conatactno = contactnumber.getText();
         int length=Conatactno.length();
         char c1 = evt.getKeyChar();
         if(evt.getKeyChar()>='0'&&evt.getKeyChar()<='9')
         {
             if(length<10)
             {
                 contactnumber.setEditable(true);
             }
             else
             {
                 
                  contactnumber.setEditable(false);
             }
         }
         else{
             if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
             {
                 contactnumber.setEditable(true);
             }
             else
             {
                 
                  contactnumber.setEditable(false);
             }
         
         }

    }//GEN-LAST:event_contactnumberKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cadders;
    private javax.swing.JTextField cemail;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField contactnumber;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField pamt;
    private javax.swing.JTextField pcname;
    private javax.swing.JTextField pdesc;
    private javax.swing.JTextField pmodelno;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField pqty;
    private javax.swing.JTextField prate;
    private javax.swing.JTextField prmt;
    private javax.swing.JTextField tamt;
    // End of variables declaration//GEN-END:variables
}
